### ISSUE TITLE
/temp crashes MoonCord

### ISSUE THREAD

**Issue by cowboy3d** [eliteSchwein/mooncord#102]
Calling /temp crashes mooncard at discord/commands/temp.js, line 114.
Problem seems to be that moonraker doesn't report power for temperature fans, only temperatures, targets and speeds - therefore the access to powers crashes the program.

![MoonCord](https://user-images.githubusercontent.com/70490637/129200144-5d8eda43-c47f-424c-9780-8fb0e6ae65f8.jpg)

A simple fix to use speeds instead of powers in line 114 works (at least for me):
                const speed = calculatePercent(temps[temp].speeds[temps[temp].speeds.length - 1])

Let me know if you need further input.

Kind regards

Stephan

**Comment by eliteSchwein** [comment]
Good to know, i dont have a heat fan actuelly, thank you very much for the Details :)
