### ISSUE TITLE
You do not have Permissions

### ISSUE THREAD

**Issue by vertigo235** [eliteSchwein/mooncord#106]
OK, another dumb issue.

The bot keeps telling me I do not have permissions, I'm the guild owner and I added my ID to the controllers section of the json file.

![image](https://user-images.githubusercontent.com/1238461/129482744-ace74f70-17db-4646-b337-3bc0825fa65f.png)

![image](https://user-images.githubusercontent.com/1238461/129482766-bb6e9965-18b9-44ad-a2cd-4ec970df9774.png)

**Comment by eliteSchwein** [comment]
the id needs to be in between 2 "

**Comment by vertigo235** [comment]
ah, of course that's the only thing I didn't try (although I did try single quotes)
