### ISSUE TITLE
Update complicated from 0.3.1 to 0.4.0

### ISSUE THREAD

**Issue by top-gun** [eliteSchwein/mooncord#119]
I installed MoonCord 0.3.1 on my Fluiddpi which uses the most current Klipper, Moonraker and OS files.

As I just got the update notification for 0.4.0, I updated via the Fluidd-UI. During the update, I noticed some warnings about cleaning up folders in NPM.

After the update, MoonCord no longer worked, I got only "this interaction has failed" to any command.

Steps I took to resolve the issue (successfully):

1.) sudo chmod +X +R and +W for the folder "scripts" (I could only see the filenames, not even read permissions)
2.) sudo ./migrateNode.sh (this was probably unnecessary, I got a warning from the updater)
3.) ./migrateNode.sh (as Pi, no su rights)

After a restart and a few minutes, MoonCord is working again.

I suggest:
1.) Definitely fix permissions on the scripts folter
2.) If possible perform the node.js-update automatically
3.) Adjust the Wiki so people know how to upgrade correctly.

**Comment by eliteSchwein** [comment]
I stated already on a newer issue, i am aware about the bugs in 0.0.4, before i released it, it worked great... I tested it very deeply till there where no issues anymore, but every setup is different it seems like, i try to fix the issues asap

**Comment by top-gun** [comment]
Thank you for your enormous effort. The software is very handy and I prefer it over VPN when I'm not at home. :)

**Comment by eliteSchwein** [comment]
resolved in 0.0.5
