### ISSUE TITLE
/notifyme not working

### ISSUE THREAD

**Issue by DrFailbucket** [eliteSchwein/mooncord#165]
I had a little bit of trouble with setting everthing up, but could figured it out. In the Wiki there acrucial Infos missing.

But my problem actually is that the /notifyme is not working. 

When i send the command i get the report " I will notify you....blabla" but when the Print is started or finished i don't recived any message.

**Comment by eliteSchwein** [comment]
Hello there, the current Version is kinda buggy, i am currently working on a recode but it will take some time

**Comment by eliteSchwein** [comment]
resolved in 0.0.5
