### ISSUE TITLE
Add flip option to camera (/status) output

### ISSUE THREAD

**Issue by stefanpausch** [eliteSchwein/mooncord#19]
Please add an option to flip the webcam (f.e. on status) - My webcam is mounted upside down.

![image](https://user-images.githubusercontent.com/184467/116784718-117aaa00-aa96-11eb-9f35-a99a0f47952f.png)

**Comment by eliteSchwein** [comment]
will come with 0.0.3

**Comment by eliteSchwein** [comment]
https://github.com/eliteSchwein/mooncord/wiki/Camera-Configuration

**Comment by eliteSchwein** [comment]
implemented in the dev tree

a8ed6188ff4605aec7533a2aa32f37113ecd41be
2091edc028fe320c279a2701bbe5f5ccec86c2f0
be8c59e323853bf2caa4f419edb0da8c826b769a
