### ISSUE TITLE
Progress updates are not using the same embed as they once did

### ISSUE THREAD

**Issue by samwiseg0** [eliteSchwein/mooncord#210]
When the progress is updated it sends a new message instead of updating the original embed. 
<img width="675" alt="Screen Shot 2022-01-10 at 2 29 01 PM" src="https://user-images.githubusercontent.com/2241731/148827228-cbe2296a-4738-4345-a6de-d47b574904b3.png">
<img width="658" alt="Screen Shot 2022-01-10 at 2 29 07 PM" src="https://user-images.githubusercontent.com/2241731/148827247-fdcd861d-61c6-4406-9f7c-06641e6f5f68.png">

**Comment by eliteSchwein** [comment]
resolved with 960da004d7a5bd1c967f8408d473bdaa8d6824d1
