### ISSUE TITLE
[ENHACEMENT] Only display the date in ETA Print Time if not today

### ISSUE THREAD

**Issue by samwiseg0** [eliteSchwein/mooncord#211]
If the print end time is today. Only show the time and not the date. 
<img width="153" alt="Screen Shot 2022-01-10 at 2 40 34 PM" src="https://user-images.githubusercontent.com/2241731/148828648-94be3231-2612-4959-9803-7ee68de1a0a8.png">

**Comment by eliteSchwein** [comment]
implemented with eeda7d2e5f67e26738d0cde45c39cba7bbdbf08a

**Comment by eliteSchwein** [comment]
i will add some logic to idd, somehow

**Comment by eliteSchwein** [comment]
smart timestamp implemented with 4c36d8e9cc8ae705307cc29cc43216f7377c8970
