### ISSUE TITLE
Status, Gcode execute

### ISSUE THREAD

**Issue by sashi** [eliteSchwein/mooncord#288]
Hello
Using latest mooncord
I have this in my status

    "status": {
        "update_interval": 10,
        "use_percent": true,
        "min_interval": 15,
        "before": {
            "enable": true,
            "delay": 5,
            "execute": [ "gcode: lighton" ]
        },
        "after": {
            "enable": true,
            "delay": 5,
            "execute": [ "gcode: lightoff" ]
        }
    },

The before gcode execution works  however the after never seems to execute.
Thanks

**Comment by eliteSchwein** [comment]
Hey there

this should be fixed with 1.0.0

**Comment by eliteSchwein** [comment]
about that, i found the issue... i did a typo, it is now tested and fixed with 1.0.0

fixed with f99e8a7c25d97e307bf63c3f2fd93edac9df8b6b

**Comment by eliteSchwein** [comment]
Hey there any updates?

**Comment by sashi** [comment]
This is fixed now thanks

**Comment by sashi** [comment]
Hello elite.
Sorry not sure what happened. It is only doing my before now.
Also the bot itself no longer does status updates automatically

**Comment by eliteSchwein** [comment]
Hey there, can you pls take a look into your log and post any error message?

**Comment by sashi** [comment]
No errors in mooncord log

> [info] [2022-11-15T05:18:36.319Z] retrieved Thumbnail for Peg-TronXY X5SA-PETG.gcode
[info] [2022-11-15T05:18:52.354Z] Broadcast Message: Homing All...
[info] [2022-11-15T05:23:47.724Z] Broadcast Message: Waiting for Temps
[info] [2022-11-15T05:23:48.728Z] Broadcast Message: Prime Line
[info] [2022-11-15T05:24:09.541Z] Broadcast Message: Printing.....
[info] [2022-11-15T05:24:10.713Z] print is to 0% complete...
[info] [2022-11-15T05:25:50.093Z] print is to 1% complete...
[info] [2022-11-15T05:27:42.171Z] print is to 2% complete...
[info] [2022-11-15T05:29:37.250Z] print is to 3% complete...
[info] [2022-11-15T05:31:10.541Z] print is to 4% complete...
[info] [2022-11-15T05:33:14.961Z] print is to 5% complete...
[info] [2022-11-15T05:35:18.354Z] print is to 6% complete...
[info] [2022-11-15T05:37:11.708Z] print is to 7% complete...
[info] [2022-11-15T05:38:36.219Z] print is to 8% complete...
[info] [2022-11-15T05:40:42.865Z] print is to 9% complete...
[info] [2022-11-15T05:42:46.999Z] print is to 10% complete...
[info] [2022-11-15T05:44:42.645Z] print is to 11% complete...
[info] [2022-11-15T05:45:58.634Z] print is to 12% complete...
[info] [2022-11-15T05:48:09.620Z] print is to 13% complete...
[info] [2022-11-15T05:50:21.317Z] print is to 14% complete...
[info] [2022-11-15T05:51:36.149Z] File .thumbs/TXXPRO2ED01P_FillRight.png changed: create_file
[info] [2022-11-15T05:51:36.150Z] Retrieve Config Files...
[info] [2022-11-15T05:51:36.156Z] File .thumbs/TXXPRO2ED01P_FillRight-32x32.png changed: create_file
[info] [2022-11-15T05:51:36.157Z] Retrieve Config Files...
[info] [2022-11-15T05:51:36.256Z] File TXXPRO2ED01P_FillRight.gcode changed: create_file
[info] [2022-11-15T05:51:36.257Z] Retrieve current GCode Files...
[info] [2022-11-15T05:51:36.272Z] File TXXPRO2ED01P_FillRight.gcode changed: modify_file
[info] [2022-11-15T05:51:36.274Z] Retrieve current GCode Files...
[info] [2022-11-15T05:52:14.167Z] print is to 15% complete...
[info] [2022-11-15T05:52:31.367Z] File .thumbs/TXXPRO2ED01P_FillRight.png changed: modify_file
[info] [2022-11-15T05:52:31.368Z] Retrieve Config Files...
[info] [2022-11-15T05:52:31.385Z] File .thumbs/TXXPRO2ED01P_FillRight-32x32.png changed: modify_file
[info] [2022-11-15T05:52:31.386Z] Retrieve Config Files...
[info] [2022-11-15T05:52:31.388Z] File TXXPRO2ED01P_FillRight.gcode changed: modify_file
[info] [2022-11-15T05:52:31.390Z] Retrieve current GCode Files...
[info] [2022-11-15T05:52:31.392Z] File TXXPRO2ED01P_FillRight.gcode changed: modify_file
[info] [2022-11-15T05:52:31.394Z] Retrieve current GCode Files...
[info] [2022-11-15T05:53:32.908Z] print is to 16% complete...
[info] [2022-11-15T05:55:41.580Z] print is to 17% complete...
[info] [2022-11-15T05:57:48.489Z] print is to 18% complete...
[info] [2022-11-15T05:59:50.924Z] print is to 19% complete...
[info] [2022-11-15T06:01:01.883Z] print is to 20% complete...
[info] [2022-11-15T06:03:10.810Z] print is to 21% complete...
[info] [2022-11-15T06:05:22.013Z] print is to 22% complete...
[info] [2022-11-15T06:07:26.653Z] print is to 23% complete...
[info] [2022-11-15T06:08:36.402Z] print is to 24% complete...
[info] [2022-11-15T06:10:42.316Z] print is to 25% complete...
[info] [2022-11-15T06:12:51.513Z] print is to 26% complete...
[info] [2022-11-15T06:13:59.242Z] print is to 27% complete...
[info] [2022-11-15T06:16:12.752Z] print is to 28% complete...
[info] [2022-11-15T06:18:23.994Z] print is to 29% complete...
[info] [2022-11-15T06:20:35.286Z] print is to 30% complete...
[info] [2022-11-15T06:21:39.024Z] print is to 31% complete...
[info] [2022-11-15T06:23:45.510Z] print is to 32% complete...
[info] [2022-11-15T06:25:51.738Z] print is to 33% complete...
[info] [2022-11-15T06:27:57.943Z] print is to 34% complete...
[info] [2022-11-15T06:29:00.937Z] print is to 35% complete...
[info] [2022-11-15T06:31:09.614Z] print is to 36% complete...
[info] [2022-11-15T06:33:18.039Z] print is to 37% complete...
[info] [2022-11-15T06:35:25.942Z] print is to 38% complete...
[info] [2022-11-15T06:36:28.932Z] print is to 39% complete...
[info] [2022-11-15T06:38:35.943Z] print is to 40% complete...
[info] [2022-11-15T06:40:44.430Z] print is to 41% complete...
[info] [2022-11-15T06:42:50.910Z] print is to 42% complete...
[info] [2022-11-15T06:43:53.868Z] print is to 43% complete...
[info] [2022-11-15T06:46:01.765Z] print is to 44% complete...
[info] [2022-11-15T06:48:09.710Z] print is to 45% complete...
[info] [2022-11-15T06:50:15.887Z] print is to 46% complete...
[info] [2022-11-15T06:51:21.118Z] print is to 47% complete...
[info] [2022-11-15T06:53:28.831Z] print is to 48% complete...
[info] [2022-11-15T06:55:34.769Z] print is to 49% complete...
[info] [2022-11-15T06:57:41.977Z] print is to 50% complete...
[info] [2022-11-15T06:58:45.245Z] print is to 51% complete...
[info] [2022-11-15T07:00:51.643Z] print is to 52% complete...
[info] [2022-11-15T07:02:59.802Z] print is to 53% complete...
[info] [2022-11-15T07:05:05.723Z] print is to 54% complete...
[info] [2022-11-15T07:07:11.897Z] print is to 55% complete...
[info] [2022-11-15T07:08:15.624Z] print is to 56% complete...
[info] [2022-11-15T07:10:21.611Z] print is to 57% complete...
[info] [2022-11-15T07:12:28.793Z] print is to 58% complete...
[info] [2022-11-15T07:14:35.791Z] print is to 59% complete...
[info] [2022-11-15T07:15:39.267Z] print is to 60% complete...
[info] [2022-11-15T07:17:46.964Z] print is to 61% complete...
[info] [2022-11-15T07:19:53.897Z] print is to 62% complete...
[info] [2022-11-15T07:22:00.323Z] print is to 63% complete...
[info] [2022-11-15T07:23:04.542Z] print is to 64% complete...
[info] [2022-11-15T07:25:12.545Z] print is to 65% complete...
[info] [2022-11-15T07:27:22.214Z] print is to 66% complete...
[info] [2022-11-15T07:29:29.657Z] print is to 67% complete...
[info] [2022-11-15T07:30:35.859Z] print is to 68% complete...
[info] [2022-11-15T07:32:43.005Z] print is to 69% complete...
[info] [2022-11-15T07:34:46.647Z] print is to 70% complete...
[info] [2022-11-15T07:36:52.563Z] print is to 71% complete...
[info] [2022-11-15T07:37:54.788Z] print is to 72% complete...
[info] [2022-11-15T07:39:55.949Z] print is to 73% complete...
[info] [2022-11-15T07:42:04.884Z] print is to 74% complete...
[info] [2022-11-15T07:44:06.591Z] print is to 75% complete...
[info] [2022-11-15T07:44:34.080Z] File .mooncord.json.swp changed: create_file
[info] [2022-11-15T07:44:34.081Z] Retrieve Config Files...
[info] [2022-11-15T07:44:38.244Z] File .mooncord.json.swp changed: delete_file
[info] [2022-11-15T07:44:38.247Z] Retrieve Config Files...
[info] [2022-11-15T07:44:38.252Z] File .mooncord.json.swp changed: create_file
[info] [2022-11-15T07:44:38.253Z] Retrieve Config Files...
[info] [2022-11-15T07:44:56.467Z] File mooncord.json changed: modify_file
[info] [2022-11-15T07:44:56.471Z] Retrieve Config Files...
[info] [2022-11-15T07:44:56.719Z] File .mooncord.json.swp changed: delete_file
[info] [2022-11-15T07:44:56.720Z] Retrieve Config Files...

**Comment by sashi** [comment]
Sorry hit the wrong button but yes no logs in there as above

**Comment by eliteSchwein** [comment]
Odd, i will add more details to the log while doing the gcodes... Maybe that tells more whats happening

**Comment by eliteSchwein** [comment]
should be fixed now
