### ISSUE TITLE
/editchannel not working - Empty list of channels

### ISSUE THREAD

**Issue by ullbergm** [eliteSchwein/mooncord#318]
I have reinstalled several times just to be sure, clearing the config each time.
I have tried new bot tokens.

When i try to run /editchannel the GUI does not show me a list of channels to choose from:
![mooncord channels](https://github.com/eliteSchwein/mooncord/assets/273876/3846a244-3637-41d2-8dda-78b49fe9e61b)

Everything else seems to work, no errors on the console and i used the link listed there.
![mooncord error](https://github.com/eliteSchwein/mooncord/assets/273876/9d04db00-7bd0-4235-b6a8-92a7b1ab4f43)

**Comment by eliteSchwein** [comment]
hey there, are you using the command in dm or on a server?

**Comment by ullbergm** [comment]
I'm an idiot, lol. I didn't realize it would work in any channel. It's all good.
