### ISSUE TITLE
Add Wiki with Discord Usage

### ISSUE THREAD

**Issue by theely** [eliteSchwein/mooncord#319]
Hi there,
unfortunately it's not possible to send a pull request for a wiki page so instead I am opening this issue.

Would be great to have a Wiki Page under the "Usage" section on how to interact with the bot in Discord.
In the Page I suggest to have two sections:

1. Commands: with a list of commands the bot responds to
2. Configuration: with a list of advanced commands to configure to bot (e.g. setting up broadcasting channel)

Thanks

**Comment by eliteSchwein** [comment]
Hey there, sorry for the late response.

Yeah i will rework the wiki as soon as the next update is out

**Comment by eliteSchwein** [comment]
https://eliteschw31n.gitbook.io/mooncord/usage/discord-commands

Work in progress

**Comment by eliteSchwein** [comment]
with 1.0.5 i fully want to migrate to another wiki system that moonraker uses, easier to maintain.

**Comment by eliteSchwein** [comment]
done with 1.1.0 on here -> https://wiki.tludwig.dev/mooncord
