### ISSUE TITLE
Elegoo Neptune 4 pro Issues

### ISSUE THREAD

**Issue by michael2608H** [eliteSchwein/mooncord#321]
Hi, awesome app.

I am running a Discord Bot on Octoprint on my N3pro, but now I also want to start on the N4pro with you app.
Installation and DM the Bot all went fine, but when I leave the Installation Routine seems like that MoonCord stops to work immediately.
While in Installation I can download Config Files etc. 

Starting Mooncord afterwards with sudo systemctl start MoonCord results in Failed to start MoonCord.service: Unit MoonCord.service not found.

But as said, while in the installation I can access everything and I even get messages from Printer Status. 

![Screenshot 2024-01-28 135438](https://github.com/eliteSchwein/mooncord/assets/153854225/a475cce2-a73f-4175-8771-f13997b0afb5)

Any Idea how to solve and keep the instance up and running ?

**Comment by eliteSchwein** [comment]
is this resolved?
