### ISSUE TITLE
/notifyme only works on bot owner, not anyone else

### ISSUE THREAD

**Issue by MikevanBreePXL** [eliteSchwein/mooncord#323]
How to recreate:
- Add bot to server
- Have a friend on a different discord account execute `/notifyme`
- The bot will always give a permission error/hidden message, wether the friend has /admin or not

Expected behaviour:
Anyone in the discord can execute the command, just like /status

**Comment by MikevanBreePXL** [comment]
Hi, as stated in the initial post, it doesn't change outcome

**Comment by eliteSchwein** [comment]
hey there, sorry for the late response.

currently only discord admins or guild admins can use notifyme, this is more or less a privacy protection.

you can see the config here: https://github.com/eliteSchwein/mooncord/blob/master/scripts/mooncord_full.cfg#L551

**Comment by MikevanBreePXL** [comment]
Right on, perhaps this could be a feature request.
