### ISSUE TITLE
Discord Client Internal Timeout

### ISSUE THREAD

**Issue by sashi** [eliteSchwein/mooncord#33]
My token, application ID and key are all working as the bot is connected to my channel in discord
I have the default URLs in config.json as I installed the bot on to the klipper PI

The bot shows "Watching printer start" but no commands work

![image](https://user-images.githubusercontent.com/25265/118381610-609a0200-b5a1-11eb-99f3-aa7c445a19ab.png)

One error in mooncard status below
![image](https://user-images.githubusercontent.com/25265/118381604-4b24d800-b5a1-11eb-8284-be98d66f7d4a.png)

**Comment by eliteSchwein** [comment]
fixed in 229d4a88d7bf7030930d78500b660ece6f5a77af
