### ISSUE TITLE
Found wrong conditional

### ISSUE THREAD

**Issue by Jomik** [eliteSchwein/mooncord#330]
https://github.com/eliteSchwein/mooncord/blob/d89b35f8b9d68a58c3a69244fa3fcebb07bec7be/src/helper/PowerDeviceHelper.ts#L15
Seems to be a mistake. It should be an equality check.

**Comment by eliteSchwein** [comment]
thanks for the report, i will fix it on sunday

**Comment by eliteSchwein** [comment]
should be fixed now
