### ISSUE TITLE
Printer Status Error With Multi Printer on 1 PI

### ISSUE THREAD

**Issue by screech24** [eliteSchwein/mooncord#35]
I have Tried to install MoonCord with a Multiple Klipper Instance on 1 PI setup where each printer is served on a different moonraker Port EX. 7126 or 7125

here is the error im getting using http://127.0.0.1:7126 as the moonrakerurl in the config,json
![Error](https://user-images.githubusercontent.com/72464022/118385235-4f6de700-b5db-11eb-93b8-824e2564eb55.png)
I am also unable to Change Permissions in the discord Server but im not sure this is a related issue. 
![error 2](https://user-images.githubusercontent.com/72464022/118385242-68769800-b5db-11eb-9bdf-b2c58b3ec9ea.png)

**Comment by eliteSchwein** [comment]
From the discord converation:

Master ID is your discord id and application id is the id from your application...

Also you need to change the port on the websocket (ws://127.0.0.1:7126)

**Comment by eliteSchwein** [comment]
Solved via discord
