### ISSUE TITLE
Print time shows the slicer estimated time not the actual printed time

### ISSUE THREAD

**Issue by jarheck** [eliteSchwein/mooncord#76]
When getting the print status it shows the "Print Time" as the slicer estimated time instead of the actual print time. I am not sure if this is expected or a bug? If it is a bug maybe this is a feature request to show the actual time elapsed for the print.

**Comment by eliteSchwein** [comment]
currently i use the slicer estimated time, but i will replace it with the klipper estimated time in 0.0.3

**Comment by jarheck** [comment]
Would it be possible to get the actual elapsed time for the print in the Print Done message?

**Comment by eliteSchwein** [comment]
Sure!

**Comment by eliteSchwein** [comment]
fixed in 79ee251001cd10320eca5b6262fa204c55366a8e

**Comment by eliteSchwein** [comment]
Reopen because i made it even worser now... I will tomorrow update the methode for the time stuff

**Comment by eliteSchwein** [comment]
Finally solved with a heck lot other buggs
